[package]
name = "distributions"
version = "0.1.0"
authors = ["Nikita Gaevoy <nikgaevoy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
overload = "0.1.1"
statrs = "0.12.0"
